#ifndef LEDPATTERN_CONFIG_H_INCLUDED
#define LEDPATTERN_CONFIG_H_INCLUDED

#ifndef LED_PATTERN_REPEAT_STACK_SIZE
#define LED_PATTERN_REPEAT_STACK_SIZE (3)
#endif

// #define LED_PATTERN_FADE_UNSUPPORTED

// #define LED_PATTERN_NO_CRITICAL_SECTIONS

#endif // LEDPATTERN_CONFIG_H_INCLUDED
